/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cctCrowdSaleSol from "./CCTCrowdSale.sol";
export type { cctCrowdSaleSol };
import type * as heroSol from "./Hero.sol";
export type { heroSol };
export type { Choco } from "./Choco";
export type { HeroMarketplace } from "./HeroMarketplace";
export type { USDT } from "./USDT";
export type { Vault } from "./Vault";
